# Generated by Django 4.2.2 on 2023-06-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_city_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
